security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Doctor:
            algorithm: auto
        App\Entity\Nurse:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Security\MultiEntityUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
                # where to redirect after logout
                # target: app_any_route
            access_denied_handler: App\Security\AccessDeniedHandler
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /dashboard

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Rutas públicas
        - { path: ^/reclamo/new, roles: PUBLIC_ACCESS }
        - { path: ^/reclamo/gracias, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        
        # Rutas que requieren autenticación básica
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/consumible, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pacientes, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/liquidaciones/profesional, roles: IS_AUTHENTICATED_FULLY }
        
        # Otras rutas - se manejarán con permisos específicos en los controladores
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
